### 이벤트 생성 API 테스트
POST http://localhost:8080/admin/events
Content-Type: application/json

{
  "name": "여름 페스티벌 티켓팅",
  "openTime": "2026-08-01T20:00:00",
  "couponQuota": 100,
  "maxRow": 5,
  "maxCol": 10
}

### 유저 좌석 예매 API 테스트
POST http://localhost:8080/api/reservations
Content-Type: application/json
Session-Key: my-test-session-1234

{
  "eventId": 1,
  "seatId": 1
}
